apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Values.nameOverride | default .Chart.Name }}
spec:
  schedule: {{ .Values.schedule | quote }}
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: {{ .Values.ttlSecondsAfterFinished }}
      template:
        spec:
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            securityContext:
              {{- .Values.securityContext | toYaml | nindent 14 }}
            command: {{ .Values.Command }}
            {{- if gt (len .Values.envFromSecret) 0 }}
            env:
            {{- range $key, $value := .Values.env }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
            {{- end }}
            {{- end }}
            {{- if ne .Values.envFromSecret "" }}
            envFrom:
            - secretRef:
                name: {{ .Values.envFromSecret }}
            {{- end }}
            volumeMounts:
            {{- range $value := .Values.configmapMounts }}
            - name: {{ $value.name }}
              mountPath: {{ $value.path }}
              readOnly: true
            {{- end }}

          volumes:
          {{- range $value := .Values.configmapMounts }}
          - name: {{ $value.name }}
            configMap:
              name: {{ $value.name }}
            {{- end }}
          restartPolicy: {{ .Values.restartPolicy }}
          nodeSelector:
              {{- .Values.nodeSelector | toYaml | nindent 12 }}
          affinity:
              {{- .Values.affinity | toYaml | nindent 12 }}
          tolerations:
            {{- .Values.tolerations | toYaml | nindent 12 }}
