version: 2.1

jobs:
  publish_charts:
    docker:
      - image: quay.io/helmpack/chart-releaser
    # Run the welcome/run job in its own container
    steps:
      - checkout
      - run:
          name: install dependencies
          command: sh scripts/install_deps.sh
      - run:
          name: publish helm charts
          command: bash scripts/publish_charts.sh
      - run:
          name: update k8s_config repo
          command: bash scripts/update_k8s_config.sh
    environment:
      REPO: helm-charts
      OWNER: bcaldwell
      CHART_REPO_URL: https://charts.bcaldwell.ca


workflows:
  version: 2
  publish_charts:
    jobs:
      - publish_charts
