apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jupyter.fullname" . }}
  labels:
    {{- include "jupyter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "jupyter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jupyter.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - start-notebook.sh
          ports:
            - name: http
              containerPort: 8888
          env:
            - name: LAB_TOKEN
              value: ""
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: startup-scripts-volume
            mountPath: /usr/local/bin/start-notebook.d/
            readOnly: true
          - name: ssh-key
            mountPath: /home/bcaldwell/.ssh
            readOnly: true
      volumes:
        - name: startup-scripts-volume
          configMap:
            name: {{ include "jupyter.fullname" . }}-startup
        - name: ssh-key
          secret:
            secretName: ssh-key
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
