apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jupyter.fullname" . }}-startup
  labels:
    {{- include "jupyter.labels" . | nindent 4 }}
data:
  clone-repos.sh: |
    git clone git@github.com:bcaldwell/jupyter.git $HOME/jupyter
    git clone git@github.com:bcaldwell/notebooks.git $HOME/notebooks
  install.sh: |
    ln -sf $HOME/jupyter/Pipfile $HOME/Pipfile
    ln -sf $HOME/jupyter/Pipfile.lock $HOME/Pipfile.lock
    # pipenv install --system
