apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "stream-deck-controller.labels" . | nindent 4 }}
  name: stream-deck-controller-config
data:
  config.yaml: | {{ include "stream-deck-controller.config" . | nindent 4 }}

