apiVersion: v1
kind: Service
metadata:
  name: {{ include "stream-deck-controller.fullname" . }}
  labels:
    {{- include "stream-deck-controller.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: http
  selector: {{- include "stream-deck-controller.selectorLabels" . | nindent 4 }}
  type: ClusterIP
