apiVersion: v1
kind: Service
metadata:
  name: {{ include "stream-deck-controller.fullname" . }}
  labels:
    {{- include "stream-deck-controller.labels" . | nindent 4 }}
spec:
  ports:
  - name: stream-deck-controller
    port: 8000
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: homebridge
    app.kubernetes.io/name: homebridge
  type: ClusterIP
