apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "generic-deployment.fullname" . }}
  labels:
    {{- include "generic-deployment.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "generic-deployment.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "generic-deployment.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      hostNetwork: {{ .Values.hostNetwork }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: {{ .Values.command | toJson }}
          env: {{ .Values.env | toYaml | nindent 12 }}
          {{ if .Values.envFromSecretName }}
          envFrom:
          - secretRef:
              name: {{ .Values.envFromSecretName }}
          {{ end }}
          ports:
          - containerPort: {{ .Values.port }}
            hostPort: {{ .Values.port }}
            name: http
            protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
