apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic-deployment.fullname" . }}
  labels:
    {{- include "generic-deployment.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: {{ .Values.port }}
    protocol: TCP
    targetPort: http
  selector: {{- include "stream-deck-controller.selectorLabels" . | nindent 4 }}
  type: ClusterIP